version: '3.5'

networks:
  bov-control-network:
    name: bov-control-network

services:
  bov-control-frontend:
    container_name: bov-control-frontend
    volumes:
      - .:/usr/src/app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://challenge-front-end.bovcontrol.com/v1
      - VITE_PORT=80
    ports:
      - 80:80
    networks:
      - bov-control-network
